### ISSUE TITLE
Vagrant-azure windows provision puppet failed 

### ISSUE THREAD

**Issue by nonst0penergy** [Azure/vagrant-azure#100]
<h6>Im trying to use provision on my azure VM, but i have some error </h6>
```
PS D:\azureVM> vagrant provision
==> default: Attempting to read state for WS2008JDK in WS2008JDK-service-ggrto
==> default: VM Status: ReadyRole
==> default: Determining OS Type By Image
==> default: OS Type is Windows
    default: Looking for WinRM
C:/Users/ykyr/.vagrant.d/gems/gems/vagrant-azure-1.2.1/lib/vagrant-azure/action/read_winrm_info.rb:41:in `>': comparison
 of String with 0 failed (ArgumentError)
        from C:/Users/ykyr/.vagrant.d/gems/gems/vagrant-azure-1.2.1/lib/vagrant-azure/action/read_winrm_info.rb:41:in `s
ort'
        from C:/Users/ykyr/.vagrant.d/gems/gems/vagrant-azure-1.2.1/lib/vagrant-azure/action/read_winrm_info.rb:41:in `r
ead_winrm_info'
        from C:/Users/ykyr/.vagrant.d/gems/gems/vagrant-azure-1.2.1/lib/vagrant-azure/action/read_winrm_info.rb:20:in `c
all'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Users/ykyr/.vagrant.d/gems/gems/vagrant-azure-1.2.1/lib/vagrant-azure/action/os_type.rb:29:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/config_validate.rb:25:in `
call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Users/ykyr/.vagrant.d/gems/gems/vagrant-azure-1.2.1/lib/vagrant-azure/action/connect_azure.rb:44:in `cal
l'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:214:in `action_raw'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:191:in `block in action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:516:in `lock'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:178:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:178:in `action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/commands/provision/command.rb:30:in `block in
 execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:226:in `block in wit
h_target_vms'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:220:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/v2/command.rb:220:in `with_target_
vms'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/commands/provision/command.rb:29:in `execute'

        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/cli.rb:42:in `execute'
from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:301:in `cli'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/bin/vagrant:174:in `<main>'
```
<h6> This is my VagrantFile: </h6>

```
Vagrant.configure(2) do |config|
  config.vm.box = 'azure'
	 
  config.vm.provision :puppet, :options => ["--debug --trace --verbose"] do |puppet|
      config.vm.communicator = "winrm"
config.winrm.username = 'vagrant'
  config.winrm.password = 'vagrant'
end
    config.vm.provider :azure do |azure|
      azure.mgmt_certificate = 'certificate.pem'
      azure.mgmt_endpoint = 'https://management.core.windows.net'
      azure.subscription_id = 'id'
      azure.storage_acct_name = 'storage2015' # optional. A new one will be generated if not provided.

      azure.vm_image = '0c0083a6d9a24f2d91800e52cad83950__JDK-1.8.0_51-20150810-Win-GA'
      azure.vm_user = 'vagrant' # defaults to 'vagrant' if not provided
      azure.vm_password = 'Vagrant' # min 8 characters. should contain a lower case letter, an uppercase letter, a number and a special character

      azure.vm_name = 'WS2008JDK' # max 15 characters. contains letters, number and hyphens. can start with letters and can end with letters and numbers
      azure.vm_location = 'West Europe' # e.g., West US
      
       azure.winrm_transport = [ 'http', 'https' ] 
       # customize the winrm https port, defaults to 5986
       azure.winrm_https_port = '5986'
       # customize the winrm http port, defaults to 5985 
       azure.winrm_http_port = '5985' 
       # opens the Remote Desktop internal port (53389). 
       # Without this, you cannot RDP to a Windows VM.
       azure.tcp_endpoints = '3389:53389'
    end
config.winrm.port = '5985'
 config.vm.boot_timeout = 1000
end
```
<h6>This is read_winrm_info.rb file</h6>
```
#--------------------------------------------------------------------------
# Copyright (c) Microsoft Open Technologies, Inc.
# All Rights Reserved.  Licensed under the Apache License, Version 2.0.
# See License.txt in the project root for license information.
#--------------------------------------------------------------------------
require 'log4r'

module VagrantPlugins
  module WinAzure
    module Action
      class ReadWinrmInfo
        def initialize(app, env)
          @app = app
          @logger = Log4r::Logger.new('vagrant_azure::action::read_winrm_info')
        end

        def call(env)
          if env[:machine].config.vm.guest == :windows
            env[:ui].detail 'Looking for WinRM'
            env[:machine_winrm_info] = read_winrm_info(env[:azure_vm_service], env[:machine])
            env[:ui].detail "Found public port #{env[:machine_winrm_info][:port]}"
          end

          @app.call(env)
        end

        def read_winrm_info(azure, machine)
          return nil if machine.id.nil?
          machine.id =~ /@/
          vm = azure.get_virtual_machine($`, $')

          if vm.nil? || !vm.instance_of?(Azure::VirtualMachineManagement::VirtualMachine)
            # Machine cannot be found
            @logger.info 'Machine not found. Assuming it was destroyed'
            machine.id = nil
            return nil
          end

          types = %w(PowerShell WinRm-Http)

          endpoint = vm.tcp_endpoints.reject { |i| !types.include?(i[:name]) }.sort{ |i| i[:name] }.first
        if endpoint
            machine.config.winrm.host = "#{vm.cloud_service_name}.cloudapp.net"
            machine.config.winrm.port = endpoint[:public_port]

            if endpoint[:name] == types[0] # if it's PowerShell, then it's over https so use ssl (cert is self signed)
                machine.config.winrm.ssl_peer_verification = false
                machine.config.winrm.transport = :ssl
            end
            return {:host => "#{vm.cloud_service_name}.cloudapp.net", :port => endpoint[:public_port]}
          end
          nil
        end
      end
    end
  end
end
```

**Comment by devigned** [comment]
I'll give this a look as soon as I can. Sorry, for the delay.
