### ISSUE TITLE
You did not provide a valid 'password' value. 

### ISSUE THREAD

**Issue by wayne-o** [Azure/vagrant-azure#107]
Just getting:

```
ResourceNotFound : The hosted service does not exist.
==> default: Add Role? - false
You did not provide a valid 'password' value.
Failed to create virtual machine : You did not provide a valid 'password' value.
/Users/waynedouglas/.vagrant.d/gems/gems/azure-0.7.0/lib/azure/core/utility.rb:122:in `error_with_exit': Failed to create virtual machine : You did not provide a valid 'password' value. (RuntimeError)
    from /Users/waynedouglas/.vagrant.d/gems/gems/azure-0.7.0/lib/azure/virtual_machine_management/virtual_machine_management_service.rb:137:in `rescue in create_virtual_machine'
    from /Users/waynedouglas/.vagrant.d/gems/gems/azure-0.7.0/lib/azure/virtual_machine_management/virtual_machine_management_service.rb:96:in `create_virtual_machine'
```

I have provided a password explicitly - also provided paths for private_key_file tried one or the other and both... always tells me I haven't provided a password?

**Comment by danthecowboy** [comment]
Got the same issue, any solutions for this?

**Comment by wayne-o** [comment]
I gave up after a couple of days :/

**Comment by activatedgeek** [comment]
Did you follow this? And from my experience with the `azure-node-sdk`, `password` is a required field, whether you have the `ssh_key` or not.
```
The password that is input when prompted above must meet password complexity requirements of at least 3 of the following: 1 UPPER case letter, 1 lower case letter, 1 number and/or 1 symbol.  Note that if the password does not meet complexity requirements, the snippet below will still succeed - the password complexity requirements are not checked until after the VM restarts and the VM Agent is leveraged to apply the new password.
```

**Comment by danthecowboy** [comment]
Ok, I just tested it with a complex password and get the same issue.

**Comment by lonniev** [comment]
I was able to jump through this hoop by commenting out the lines:

``` ruby
    #config.ssh.password = 'vagrant' # If windows or user/pass auth enabled
    #config.ssh.private_key_path = '~/.ssh/id_rsa' # Your own private key. Don't use the Vagrant insecure private key
```

and uncommenting the `azure.vm_password` setting.

I suspect that this is working because the chosen VM is an Azure Windows image that probably lacks an sshd server and ssh user files.
