### ISSUE TITLE
nokogiri error

### ISSUE THREAD

**Issue by MattFenner** [Azure/vagrant-azure#117]
I don't know what i have done, but i am getting the following error when i try to run any vagrant commands.

I tried to uninstall vagrant and reinstall the azure plugin and i still get this error

```
C:/HashiCorp/Vagrant/embedded/gems/gems/nokogiri-1.6.3.1-x86-mingw32/lib/nokogiri.rb:29:in `require': cannot load such f
ile -- nokogiri/nokogiri (LoadError)
        from C:/HashiCorp/Vagrant/embedded/gems/gems/nokogiri-1.6.3.1-x86-mingw32/lib/nokogiri.rb:29:in `rescue in <top
(required)>'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/nokogiri-1.6.3.1-x86-mingw32/lib/nokogiri.rb:25:in `<top (required)
>'
        from C:/Users/mfenner/.vagrant.d/gems/gems/azure-0.7.0/lib/azure.rb:17:in `require'
        from C:/Users/mfenner/.vagrant.d/gems/gems/azure-0.7.0/lib/azure.rb:17:in `<top (required)>'
        from C:/Users/mfenner/.vagrant.d/gems/gems/vagrant-azure-1.3.0/lib/vagrant-azure/config.rb:7:in `require'
        from C:/Users/mfenner/.vagrant.d/gems/gems/vagrant-azure-1.3.0/lib/vagrant-azure/config.rb:7:in `<top (required)
>'
        from C:/Users/mfenner/.vagrant.d/gems/gems/vagrant-azure-1.3.0/lib/vagrant-azure/plugin.rb:28:in `require_relati
ve'
        from C:/Users/mfenner/.vagrant.d/gems/gems/vagrant-azure-1.3.0/lib/vagrant-azure/plugin.rb:28:in `block in <clas
s:Plugin>'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/registry.rb:27:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/registry.rb:27:in `get'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/kernel_v2/config/vm.rb:451:in `block in final
ize!'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/kernel_v2/config/vm.rb:446:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/kernel_v2/config/vm.rb:446:in `finalize!'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/config/v2/root.rb:50:in `block in finaliz
e!'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/config/v2/root.rb:49:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/config/v2/root.rb:49:in `finalize!'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/config/v2/loader.rb:21:in `finalize'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/config/loader.rb:168:in `load'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/vagrantfile.rb:28:in `initialize'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:740:in `new'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:740:in `vagrantfile'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:486:in `host'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:208:in `block in action_ru
nner'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:33:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:33:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:473:in `hook'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:722:in `unload'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/bin/vagrant:177:in `<main>'
```

**Comment by MattFenner** [comment]
i think i might have fixed it by uninstalling vagrant 1.8.0 and going back to 1.7.3

im not getting a different error, but i think it is unrelated
